export enum StatusEnum {
	PENDING="PENDING",
    APPROVED="APPROVED",
    WAITING_FOR_FINANCE_APPROVAL="WAITING_FOR_FINANCE_APPROVAL", 
    WAITING_FOR_LAND_VERIFICATION_OFFICE_APPROVAL="WAITING_FOR_LAND_VERIFICATION_OFFICE_APPROVAL", 
    REJECTED="REJECTED",
	DOCUMENTS_NOT_UPLOADED="DOCUMENTS_NOT_UPLOADED", 
    DOCUMENTS_UPLOADED="DOCUMENTS_UPLOADED"
}